baseURL = "https://blog.roastinthehell.com/"
languageCode = "zh-cn"
title = "Roast in the Hell"
theme = "harbor"

paginate = 5
DefaultContentLanguage = "zh-cn"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[Author]
  name = "wayZ"

[outputs]
    section = ["JSON", "HTML"]

[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fas fa-user fa-lg"
  url = "/about/"
  weight = 3

[[params.nav]]
  identifier = "tags"
  name = "Tags"
  icon = "fas fa-tag fa-lg"
  url = "tags"
  weight = 3

[params]
  mainSections = ["post"]
  favicon = "favicon.ico"
  custom_css = ["css/custom_style.css"]

  [params.logo]
    url = "icon.jpg"
    width = 50
    height = 50
    alt = "Logo"
